on: [push, pull_request]
name: PartialSort Build Check

jobs:
  test-linux:
    name: Build On Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-unknown-linux-gnu
          - x86_64-linux-android
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cross
      - run: cross build --release --target ${{ matrix.target }}

  test-mac:
    name: Build on Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
